name: Eslint-check
 
on:
  push:
    branches:
      - master 
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Eslint checking
        run: make lint


name: linter 
on: 
  push: 
   branches:
      - '**'

jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    uses: actions/setup-node@v1 
    with: 
    node-version: 14 - 
    run: make lint